### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by mlcarson** [zer0tonin/Mikochi#1]
The app seems to work as expected except for sorting.   It seems to be setup to be able to sort on Name or Size field but does neither -- at least on the latest docker version that I'm running.   If it wasn't intended, it would be a very nice feature to have.

**Comment by zer0tonin** [comment]
Hi @mlcarson,
Thanks for the report, this should be fixed in the latest version: [1.3.1](https://github.com/zer0tonin/Mikochi/releases/tag/1.3.1)
You can pull the 1.3.1 image to update mikochi. Make sure to clean your browser cache if you don't see any changes.
