### ISSUE TITLE
Typing into the search bar causes double requests

### ISSUE THREAD

**Issue by zer0tonin** [zer0tonin/Mikochi#11]
For some reason when we're using the search function, every request is fired twice. 
I assume this might come from a poorly defined useEffect hook.

**Comment by suyash-sneo** [comment]
Hi @zer0tonin. I'm new to OSS and am looking for a place to make my first contribution. If this issue is still up for grabs I'd like to take this up

**Comment by zer0tonin** [comment]
@suyash-sneo sure, go ahead. And don't hesitate to ask if you need help

**Comment by suyash-sneo** [comment]
Hi @zer0tonin I have raised a PR with quite a simple fix. Just removed searchQuery from a compound listener on searchQuery, refresh. searchQuery has its own listener that updates the refresh, which, in turn, can invoke the original listener

**Comment by zer0tonin** [comment]
Thanks a lot!
