### ISSUE TITLE
413 Content Too Large is silent in Mikochi

### ISSUE THREAD

**Issue by Elesh-Norn** [zer0tonin/Mikochi#14]
If your server is not configured to handle large files, it will refuse to upload and throw you a 413 error.

However, Mikochi doesn't parse this error and just hang on. It would be nice to have a popup saying that the request failed, with or without the reason.

**Comment by zer0tonin** [comment]
The solution for this kind of bugs would be to fallback to a pre-defined map for error codes -> error message, in case the error response cannot be parsed as json or the "err" key is not set

**Comment by zer0tonin** [comment]
Fixed in 1.6.0
