### ISSUE TITLE
Fix mobile table css

### ISSUE THREAD

**Issue by zer0tonin** [zer0tonin/Mikochi#16]
The mobile display of the table was never that great, but last update (1.6.2) seems to have made it worse. The name column is now small enough that it's basically vertical.

This can probably be fixed by tweaking padding and column widths.

PS: for anyone currently bothered by it, just roll back to 1.6.0

**Comment by TheShiveshNetwork** [comment]
Hey @zer0tonin is this issue still active and can be assigned to me?
