### ISSUE TITLE
Display a toast on operation success

### ISSUE THREAD

**Issue by zer0tonin** [zer0tonin/Mikochi#17]
We do not give the user any feedback whenever an operation completes succesfully. For example, when uploading a file, the user will not see anything showing that the upload was completed (aside from the file list changing).

We could create a toast and display it whenever an operation is succesful. This could work just like `ErrorContext` and have a `setSuccess` function similar to `setError`.

**Comment by AdithyaPadmashali** [comment]
Hi, @zer0tonin. Could you please assign this to me? I'll be making a PR soon

**Comment by zer0tonin** [comment]
Works now
