### ISSUE TITLE
Issues when running with a relative path

### ISSUE THREAD

**Issue by emlyn-m** [zer0tonin/Mikochi#24]
Running Mikochi from outside the main app directory causes a 404 error, regardless of whether the path used is relative or absolute.  

Observed using precompiled binary (version 1.6.2) on Arch Linux 6.12.1

**Comment by zer0tonin** [comment]
I'm not sure I understand the issue. Can you include steps to reproduce, what your folders look like and the value you use for `DATA_DIR`?

**Comment by emlyn-m** [comment]
Sorry, to clarify its more of an issue with the working directory than relative paths. Initially misunderstood what was happening hence the confusing issue name.

**Folder structure:**
/etc
  - /mikochi
      /static/
      /mikochi (executable)

 DATA_DIR is set to the default value of /data

**Steps to reproduce:**

From a directory which is not /etc/mikochi, run the command to launch the program and view it in a web browser. It will return a 404 error.

When ran with a working directory of /etc/mikochi, however, the web interface will function exactly as expected.



I initially noticed this while trying to run the executable via a systemd service, there are of course workarounds and I super recognise this isnt a critical issue but I still thought it was worth mentioning, feel free to close if this behaviour is expected :)

**Comment by zer0tonin** [comment]
I dI created an environment variable `FRONTEND_FILES` that lets you specify where the html/js files are located (defaults to `./static`). This should make the problem easier to solve for anyone running it in a configuration similar to yours.
