### ISSUE TITLE
No Auth Feature

### ISSUE THREAD

**Issue by BaccanoMob** [zer0tonin/Mikochi#7]
Hi! This a really good project for a minimalist file browser. There is a small feature I would like to request. I would like to use Authelia to login in (if I need a auth) so I can use SSO easily.

It would be nice if there is env variable like `NOAUTH=true` or `MIKOCHI_NOAUTH=true` to disable auth regardless if username and password are specified. Since there is no user/pass related function (not sure what your plans are with users), I think this just requires you to bypass the login page at the moment.

**Comment by zer0tonin** [comment]
Hello,
I just implemented your suggestion.
You can try it out the 1.5.0 release, it should work using `NO_AUTH=true`.
