### ISSUE TITLE
Clickable Folder icons to choose than just the links

### ISSUE THREAD

**Issue by BaccanoMob** [zer0tonin/Mikochi#8]
<img width="54" alt="image" src="https://github.com/zer0tonin/Mikochi/assets/82655889/0ed5288a-79d6-4c9a-a2a5-be8d0df110da">

Currently only the hyperlinks are clickable but It would be great to have the folder icons clickable as well. 

If there are clickable (mouse pointer actually changes when hovered), then this is a bug since its not working as intended.

Going back requires you to click `..` which occupies a really small space and clicking back button does not seem to go back.

**Comment by zer0tonin** [comment]
Also implemented in the 1.5.0 release!
